# -*- coding: utf-8 -*-
"""Practica2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgJUnflZb-IXCULK4XwFsWZa0bS2lLXd
"""

def RoundRobin (Procesos, q):
  Cola        = [{"nombre" :  P["nombre"], "restante" : P["burst"]} for P in Procesos] #arreglo con nombres y tiempos de los procesos
  Tiempo = 0
  Espera = {P["nombre"] : 0 for P in Procesos} #tiempo que llevan esperando los procesos en la cola

  while Cola:
    #sacamos el primer elemento disponible
    actual = Cola.pop(0)
    #sacamos estadísticas de tiempo
    turno = min(q,actual ["restante"]) #se escoge al valor más pequeño entre q y restante
    sobra = actual ["restante"] - turno
    print(f"""En el tiempo {Tiempo}, el proceso {actual ["nombre"]} correra por {turno} ms, y le falta {sobra} ms para terminar""")

    for esperando in Cola:
      Espera[esperando ["nombre"]] = Espera[esperando ["nombre"]] + turno #se suma a Espera el turno del proceso actual

    actual["restante"] = sobra #restante adquiere el valor sobrante del tiempo de vida
    Tiempo = Tiempo + turno

    if actual ["restante"] > 0: #si el tiempo de vida restante es mayor a cero, el proceso regresa al final de la cola
      Cola.append(actual)
    else:
      print(f"El proceso {actual ["nombre"]} TERMINÓ")

  promedio = sum(Espera.values()) / len(Espera)
  print(f"El tiempo promedio de espera de los procesos es de {promedio} ms")


Procesos = [
    {"nombre":"P1", "burst":8},
    {"nombre":"P2", "burst":3},
    {"nombre":"P3", "burst":2},
]

RoundRobin(Procesos, q = 2) #el quantum dura 2ms



RoundRobin(Procesos, q = 10) #el quantum dura 10ms, similar a FCFS

def FCFS (Procesos): #Eliminamos 'q' (los quantum) de los parámetros definidos
  Cola = [{"nombre" :  P["nombre"], "restante" : P["burst"]} for P in Procesos]
  Tiempo = 0
  Espera = {P["nombre"] : 0 for P in Procesos}

  while Cola:
    #En FCFS, el primer elemento que llega es el primero que se despacha
    actual = Cola.pop(0)
    #eliminamos la función min, la cual elegía la cantidad menor entre el quantum y el restante del proceso al que sae le asignaron recursos. En FCFS, al correr el proceso, el turno siempre será el valor del burst.
    turno = (actual ["restante"])
    #Sobrará siempre cero con FCFS.
    sobra = (actual ["restante"] - turno)
    print(f"""En el tiempo {Tiempo}, el proceso {actual ["nombre"]} correra por {turno} ms, y le falta {sobra} ms para terminar""") #Para el primer proceso, el tiempo será de cero, el turno de 8 ms y sobrará 0 ms.

    for esperando in Cola:
      Espera[esperando ["nombre"]] = Espera[esperando ["nombre"]] + turno #Los procesos en cola suman a la varaiable espera el tiempo de ejecución total del proceso anterior.

    actual["restante"] = sobra
    Tiempo = Tiempo + turno #A diferencia de Round Robin, el proceso contenido en la variable actual, solo sumarán una vez a la variable Tiempo, indiferntemente de su burst inicial.

    if actual ["restante"] > 0:
      Cola.append(actual) #Esta condición en FCFS, nunca se cumplirá.
    else:
      print(f"El proceso {actual ["nombre"]} TERMINÓ")

  promedio = sum(Espera.values()) / len(Espera)
  print(f"El tiempo promedio de espera de los procesos es de {promedio} ms")


Procesos = [
    {"nombre":"P1", "burst":8},
    {"nombre":"P2", "burst":3},
    {"nombre":"P3", "burst":2},
]
FCFS (Procesos) #Se llama la función FCFS.

import multiprocessing
import time
import random
#el proceso genera nums aleatorios
def productor(memoria,semaforo):
  for i in range(5): #genera 5 nums
    valor = random.randint(1,1000)
    semaforo.acquire() #es un while/espera*tarea


    #quiero leer la memoria, me interesa que otro proc no lo esté usando
    memoria[i] = valor
    semaforo.release() #signal
    time.sleep(0.15)
    #time.sleep (0.60) -> aumentamos tiempo de bloqueo en productor

#el proceso se mueve y lee
def consumidor(memoria,semaforo):
  for i in range (5): #lee 5 nums
    time.sleep(0.2)
    #time.sleep (0.60) -> aumentamos tiempo de bloqueo en consumidor
    semaforo.acquire()
    print(f"Consumidor lee: {memoria[i]} en {i}")
    semaforo.release()


##simulación de semáforo y memoria con librerías importadas
memoria = multiprocessing.Array("i", [0]*5)
#semaforo = multiprocessing.Semaphore(1)
#semaforo = multiprocessing.Semaphore(0)
semaforo = multiprocessing.Semaphore(2)
#0 Los recursos están bloqueados a otros procesos
#1 Es un mutex, los recursos están disponibles a un proceso
#2 mutex, coordinados


##Se crean 2 procesos
ProcProductor = multiprocessing.Process(target = productor,
                                        args=(memoria,semaforo))
ProcConsumidor = multiprocessing.Process(target = consumidor,
                                        args=(memoria,semaforo))


#una vez que un proceso termina sus tareas hay que matarlo
#pareciera que se lanzan a diferentes momentos, pero los proc son voraeces, buscaran la forma de volver a trabajar, yendo al scheduling
ProcProductor.start()
ProcConsumidor.start()
##se junta con el proceso padre
ProcProductor.join()
ProcConsumidor.join()