# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bB-8jn-v0P8qn4XlcBnhPIOGna7bSWgr
"""

import os
import sys

def MostrarPCB(Pid,Etiqueta):
  #Dos espacios
  Campos = [
      "Name",
      "state",
      "Pid",
      "PPid",
      "VmSize",
      "VmRSS",
      "voluntary_ctxt_switches",

  ]
  print(f"Mostrando PCB de {Etiqueta}")

  for campo in Campos:
    with open(f"/proc/{Pid}/status") as F:
      for Linea in F:
        if Linea.startswith(campo):
          print(f"{Linea}")

print("Fuera")

print("EJERCICIO 1 Inspección de PCB de padre e hijo")

print(f"PADRE PID {os.getpid()}")
MostrarPCB(os.getpid(), "PROCESO PADRE")


Pid = os.fork()

print("Creando proceso hijo")
Pid = os.fork()
print(f"Estado {Pid}")

print("Creando proceso hijo")
Pid = os.fork()
print(f"Estado {Pid}")
if Pid == 0:
  print("Soy el HIJO")
  print(f"[HIJO] PID {os.getpid()}")
  print(f"[HIJO] PPID {os.getppid ()}")
  print(f"[HIJO] Mostrando mi PCB...")
  MostrarPCB(os.getpid(), "HIJO")

  sys.exit(0) #El proceso se acaba o muera

else:
  print(f"[PADRE] soy el padre de {Pid}")

os.waitpid(Pid,0) #Cosecha al hijo y libera su PCB



"""Ejericio 2 Zoombificación"""

import os
import sys
import time



def MostrarEstado(Pid,Etiqueta):

    with open(f"/proc/{Pid}/status") as F:
      for Linea in F:
        if Linea.startswith("State"):
          print(f"[{Etiqueta}] {Linea.strip()}")

Pid = os.fork()

if Pid == 0:
  print(f"[HIJO] PID {os.getpid()}")
  sys.exit(0)

print("[PADRE] durmiendo por 2s")
time.sleep(2)
MostrarEstado(Pid, "ZOMBIE ACTIVO")

!ps aux  | grep -E  "Z"

"""#Ejercicio 3 Proceso huérfano
## markdown
"""

Pid = os.fork()

if Pid == 0:

  PpidInicial = os.getppid()
  print(f"[HIJO] PID {os.getpid()} - PPID inicial: {PpidInicial}")
  print("[HIJO] durmiendo por 2s. El padrte terminará antes que yo")
  time.sleep(2)

  PpidFinal = os.getppid()
  print(f"[HIJO] Mi padre ya o existe {PpidInicial}")
  print(f"[HIJO] Me adopto el proceso: {PpidFinal}")
  sys.exit(0)

print(f"[PADRE]N PID {os.getpid()} TERMINA ANTES QUE EL HIJO")
print("Sin waitpid el hijo quedará huérfano")
print("se reasigna")